let fakeProductList = [
    {
        id: '1',
        name: '燒肉粽',
        description: '燒肉粽',
        discount: 1,
        price: 100,
        isSaleout: false,
        isHot: true,
        hasTool: false,
        isNew: false,
        isBrand: false,
        cookingTime: 30,
        toolPrice: 10,
        image: 'fake1.png',
    },
    {
        id: '2',
        name: '韓式泡菜炒飯',
        description: '韓式泡菜炒飯',
        discount: 0.8,
        price: 100,
        isSaleout: false,
        isHot: false,
        hasTool: false,
        isNew: false,
        isBrand: false,
        cookingTime: 30,
        toolPrice: 10,
        image: 'fake2.png',
    },
    {
        id: '3',
        name: '廣東撈麵',
        description: '廣東撈麵',
        discount: 0.8,
        price: 100,
        isSaleout: true,
        isHot: false,
        hasTool: false,
        isNew: false,
        isBrand: false,
        cookingTime: 30,
        toolPrice: 10,
        image: 'fake3.png',
    },
    {
        id: '4',
        name: '新加坡叻沙',
        description: '新加坡叻沙',
        discount: 1,
        price: 95,
        isSaleout: false,
        isHot: false,
        hasTool: true,
        isNew: false,
        isBrand: false,
        cookingTime: 30,
        toolPrice: 10,
        image: 'fake4.png',
    },
    {
        id: '5',
        name: '薑黃烤雞飯',
        description: '薑黃烤雞飯',
        discount: 1,
        price: 80,
        isSaleout: true,
        isHot: false,
        hasTool: false,
        isNew: false,
        isBrand: false,
        cookingTime: 30,
        toolPrice: 10,
        image: 'fake5.png',
    },
    {
        id: '6',
        name: '義大利香料豬肉海鮮麵義大利',
        description: '義大利香料豬肉海鮮麵義大利香料豬肉海鮮',
        price: 60,
        isSaleout: false,
        hasTool: false,
        isHot: false,
        discount: 1,
        isNew: true,
        isBrand: true,
        cookingTime: 30,
        toolPrice: 10,
        image: 'fake6.png',
    },
    {
        id: '7',
        name: '義大利香料牛肉海鮮麵',
        description: '義大利香料牛肉海鮮麵',
        price: 95,
        isSaleout: false,
        hasTool: true,
        isHot: false,
        discount: 1,
        isNew: true,
        isBrand: true,
        cookingTime: 30,
        toolPrice: 10,
        image: 'fake1.png',
    },
]
let  fakeAisleList = [
    {
        id: '1',
        aisleName: '001',
        productID: '1',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-08-01',
        state: 'normal',
    },
    {
        id: '2',
        aisleName: '002',
        productID: '2',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-08-01',
        state: 'normal',
    },
    {
        id: '3',
        aisleName: '003',
        productID: '3',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-08-01',
        state: 'normal',
    },
    {
        id: '4',
        aisleName: '004',
        productID: '4',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-08-01',
        state: 'normal',
    },
    {
        id: '5',
        aisleName: '005',
        productID: '5',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-08-01',
        state: 'normal',
    },
    {
        id: '6',
        aisleName: '006',
        productID: '6',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-08-01',
        state: 'normal',
    },
    {
        id: '7',
        aisleName: '007',
        productID: '7',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-08-01',
        state: 'normal',
    },
    {
        id: '8',
        aisleName: '008',
        productID: '1',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-09-01',
        state: 'normal',
    },
    {
        id: '9',
        aisleName: '009',
        productID: '2',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-09-01',
        state: 'normal',
    },
    {
        id: '10',
        aisleName: '010',
        productID: '3',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-09-01',
        state: 'normal',
    },
    {
        id: '11',
        aisleName: '011',
        productID: '4',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-09-01',
        state: 'normal',
    },
    {
        id: '12',
        aisleName: '012',
        productID: '5',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-09-01',
        state: 'normal',
    },
    {
        id: '13',
        aisleName: '013',
        productID: '6',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-09-01',
    },
    {
        id: '14',
        aisleName: '014',
        productID: '7',
        fullCount: 10,
        stockCount: 5,
        restockCount: 0,
        shelfLifeDate: '2023-09-01',
    }
]
module.exports = {
    fakeProductList,
    fakeAisleList,
}