# fly.toml app configuration file generated for cu-to-go-mock on 2023-07-14T06:53:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cu-to-go-mock"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
